### ISSUE TITLE
Authelia not working

### ISSUE THREAD

**Issue by 00ihsan** [9p4/jellyfin-plugin-sso#115]
Followed the profiders guide

------LOG------
[2023-04-08 04:10:29.663 +00:00] [ERR] [69] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/sso/OID/r/Authelia".
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Jellyfin.Plugin.SSO_Auth.Api.SSOController.OidPost(String provider, String state)
   at lambda_method1094(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2023-04-08 04:10:31.254 +00:00] [INF] [57] Jellyfin.Plugin.SSO_Auth.Api.SSOController: SSO Controller initialized

------Authelia settings------
    - id: jellyfin
      description: Placeholder
      secret: 'PLACEHOLDER'
      authorization_policy: two_factor
      redirect_uris:
        - https://jelly.domain.ext/sso/OID/r/Authelia
      scopes:
      - openid
      - groups
      userinfo_signing_algorithm: none

------Jellyfin------

<img width="804" alt="image" src="https://user-images.githubusercontent.com/57139073/230703032-50d3a3e6-8bac-4059-a7ea-e09449267668.png">

<img width="798" alt="image" src="https://user-images.githubusercontent.com/57139073/230703122-db275a5e-8ca6-4cf4-bc22-e0ac0a00bc1c.png">

**Comment by 9p4** [comment]
To initiate the flow, you have to visit https://jellyfin.example.com/sso/OID/p/authelia . (note the "p" and "r" in the path)

**Comment by 00ihsan** [comment]
Hi. Thanks, but still same result.

**Comment by 9p4** [comment]
The capitalization must also match the name: if your provider is called "Authelia", then you have to visit https://jellyfin.example.com/sso/OID/p/Authelia

**Comment by 9p4** [comment]
Furthermore, the OID endpoint must also be WITHOUT the "well-known" section.

**Comment by 00ihsan** [comment]
Now i get 

{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls

**Comment by 9p4** [comment]
Can you upload your Jellyfn plugn XML configuration?

**Comment by 00ihsan** [comment]
Where can i find it?

**Comment by 9p4** [comment]
In your Jellyfin configuration folder, go into `plugins/configurations` and upload the file `SSO-Auth.xml`

**Comment by 00ihsan** [comment]
Found it

**Comment by 9p4** [comment]
Can you upload it?

**Comment by 00ihsan** [comment]
<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <SamlConfigs />
  <OidConfigs>
    <item>
      <key>
        <string>Authelia</string>
      </key>
      <value>
        <PluginConfiguration>
          <OidEndpoint>https://auth.ihsansoft.nl</OidEndpoint>
          <OidClientId>jellyfin</OidClientId>
          <OidSecret>cuuyighboi7tf76utfv8tiyguvc75eyr6wy53sw5x3463s4d8790puob0b8yofi63lkboi75r7w6e789hub8kg85736a526574fobuonhkcjurxc</OidSecret>
          <Enabled>true</Enabled>
          <EnableAuthorization>true</EnableAuthorization>
          <EnableAllFolders>true</EnableAllFolders>
          <EnabledFolders />
          <AdminRoles>
            <string>Admin</string>
          </AdminRoles>
          <Roles />
          <EnableFolderRoles>false</EnableFolderRoles>
          <FolderRoleMappings />
          <RoleClaim>groups</RoleClaim>
          <OidScopes />
          <CanonicalLinks />
        </PluginConfiguration>
      </value>
    </item>
    <item>
      <key>
        <string />
      </key>
      <value>
        <PluginConfiguration>
          <OidEndpoint>https://auth.ihsansoft.nl</OidEndpoint>
          <OidClientId>jellyfin</OidClientId>
          <OidSecret>63f030ff13b93e5fd833b2be456a47393e62b100f3dae501cf8cf815f64e2e468714eee3fc2e7c4b58509f42be0ee06e369ae6e6c5b126d6c9f34604f62fc334a9522feb8a321024e4bceb77b54554e739cf28899fd8e6a09e079c457fa5fd68</OidSecret>
          <Enabled>true</Enabled>
          <EnableAuthorization>true</EnableAuthorization>
          <EnableAllFolders>true</EnableAllFolders>
          <EnabledFolders />
          <AdminRoles>
            <string>Admin</string>
          </AdminRoles>
          <Roles />
          <EnableFolderRoles>false</EnableFolderRoles>
          <FolderRoleMappings />
          <RoleClaim>groups</RoleClaim>
          <OidScopes />
          <CanonicalLinks />
        </PluginConfiguration>
      </value>
    </item>
  </OidConfigs>
</PluginConfiguration>

**Comment by 00ihsan** [comment]
SSO-Auth.xml
https://cloud.ihsansoft.nl/sharing/ol8RqGGE0

**Comment by 00ihsan** [comment]
Password:GitHub

**Comment by 00ihsan** [comment]
Can you send me a config that works? then all i have to trey is renaming it to my specs

**Comment by 00ihsan** [comment]
<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <SamlConfigs />
  <OidConfigs>
    <item>
      <key>
        <string>Authelia</string>
      </key>
      <value>
        <PluginConfiguration>
          <OidEndpoint>https://auth.domain.ext</OidEndpoint>
          <OidClientId>jellyfin</OidClientId>
          <OidSecret>PLACEHOLDER</OidSecret>
          <Enabled>true</Enabled>
          <EnableAuthorization>false</EnableAuthorization>
          <EnableAllFolders>false</EnableAllFolders>
          <EnabledFolders />
          <AdminRoles />
          <Roles />
          <EnableFolderRoles>false</EnableFolderRoles>
          <FolderRoleMappings />
          <RoleClaim>groups</RoleClaim>
          <OidScopes>
            <string>openid profile email groups</string>
          </OidScopes>
          <CanonicalLinks />
        </PluginConfiguration>
      </value>
    </item>
  </OidConfigs>
</PluginConfiguration>

**Comment by 00ihsan** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <SamlConfigs />
  <OidConfigs>
    <item>
      <key>
        <string>Authelia</string>
      </key>
      <value>
        <PluginConfiguration>
          <OidEndpoint>https://AUTH.DOMAIN.EXT</OidEndpoint>
          <OidClientId>jellyfin</OidClientId>
          <OidSecret>PLACEHOLDER</OidSecret>
          <Enabled>true</Enabled>
          <EnableAuthorization>false</EnableAuthorization>
          <EnableAllFolders>false</EnableAllFolders>
          <EnabledFolders />
          <AdminRoles />
          <Roles />
          <EnableFolderRoles>false</EnableFolderRoles>
          <FolderRoleMappings />
          <RoleClaim>groups</RoleClaim>
          <OidScopes>
            <string>openid profile email groups</string>
          </OidScopes>
          <CanonicalLinks />
        </PluginConfiguration>
      </value>
    </item>
  </OidConfigs>
</PluginConfiguration>`

**Comment by 9p4** [comment]
For reference, the file that was uploaded is:

```xml
<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <SamlConfigs />
  <OidConfigs>
    <item>
      <key>
        <string>Ihsansoft-ID</string>
      </key>
      <value>
        <PluginConfiguration>
          <OidEndpoint>https://auth.example.com</OidEndpoint>
          <OidClientId>jellyfin</OidClientId>
          <OidSecret>REDACTED</OidSecret>
          <Enabled>true</Enabled>
          <EnableAuthorization>false</EnableAuthorization>
          <EnableAllFolders>false</EnableAllFolders>
          <EnabledFolders />
          <AdminRoles />
          <Roles />
          <EnableFolderRoles>false</EnableFolderRoles>
          <FolderRoleMappings />
          <RoleClaim>groups</RoleClaim>
          <OidScopes>
            <string>openid profile email groups</string>
          </OidScopes>
          <CanonicalLinks />
        </PluginConfiguration>
      </value>
    </item>
  </OidConfigs>
</PluginConfiguration>
```

For reference, my operational configuration looks like:

```xml
<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <SamlConfigs />
  <OidConfigs>
    <item>
      <key>
        <string>kc</string>
      </key>
      <value>
        <PluginConfiguration>
          <OidEndpoint>https://auth.example.com</OidEndpoint>
          <OidClientId>jellyfin</OidClientId>
          <OidSecret>redacted</OidSecret>
          <Enabled>true</Enabled>
          <EnableAuthorization>true</EnableAuthorization>
          <EnableAllFolders>true</EnableAllFolders>
          <EnabledFolders />
          <AdminRoles>
            <string>jellyfin_admin</string>
          </AdminRoles>
          <Roles>
            <string>jellyfin</string>
          </Roles>
          <EnableFolderRoles>false</EnableFolderRoles>
          <FolderRoleMappings />
          <RoleClaim>roles</RoleClaim>
          <OidScopes />
          <DefaultProvider>Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider</DefaultProvider>
          <CanonicalLinks />
        </PluginConfiguration>
      </value>
    </item>
  </OidConfigs>
</PluginConfiguration>
```

**Comment by 00ihsan** [comment]
it looks like its working after sime debugging.

How can i forward the login page to jellyfin? so i have to use authilia and not jellyfin?

**Comment by 9p4** [comment]
For reference to anyone else who is using the plugin, can you share your fix?

> How can i forward the login page to jellyfin? so i have to use authilia and not jellyfin?

Can you elaborate on this?

**Comment by 00ihsan** [comment]
> For reference to anyone else who is using the plugin, can you share your fix?

This is the config I use to access the plugin via https://jelly.domain.com/sso/OID/p/Authelia

Authelia config:

`
id: jellyfin
      description: jellyfin
      secret: RETRACTED
      authorization_policy: two_factor
      redirect_uris:
        - https://jelly.domain.com/sso/OID/r/Authelia
      scopes:
      - openid
      - profile
      - groups
      userinfo_signing_algorithm: none
`

Plugin config:

`<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <SamlConfigs />
  <OidConfigs>
    <item>
      <key>
        <string>Authelia</string>
      </key>
      <value>
        <PluginConfiguration>
          <OidEndpoint>https://auth.domain.com</OidEndpoint>
          <OidClientId>jellyfin</OidClientId>
          <OidSecret>RETRACTED</OidSecret>
          <Enabled>true</Enabled>
          <EnableAuthorization>true</EnableAuthorization>
          <EnableAllFolders>true</EnableAllFolders>
          <EnabledFolders />
          <AdminRoles>
            <string>jellyfin_admin</string>
          </AdminRoles>
          <Roles>
            <string>jellyfin</string>
          </Roles>
          <EnableFolderRoles>false</EnableFolderRoles>
          <FolderRoleMappings />
          <RoleClaim>groups</RoleClaim>
          <OidScopes>
            <string>groups</string>
          </OidScopes>
          <DefaultProvider>Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider</DefaultProvider>
        </PluginConfiguration>
      </value>
    </item>
  </OidConfigs>
</PluginConfiguration>`

**Comment by 00ihsan** [comment]
> Can you elaborate on this?

So now when i go to jelly.domain.com I get the default Login page of jellyfin. I want to redirect jelly.domain.com to jelly.domain.com/sso/UID/p/Authelia.

**Comment by 9p4** [comment]
See https://github.com/9p4/jellyfin-plugin-sso/issues/16 and https://github.com/9p4/jellyfin-plugin-sso/issues/109
