### ISSUE TITLE
delete user wouldn't unlink it

### ISSUE THREAD

**Issue by leoleoasd** [9p4/jellyfin-plugin-sso#124]
**Describe the bug**
If I delete a user from admin page **without unlink it**, then trying to login with the same OIDC user, it will give Null Pointer Exception.

**To Reproduce**

1. create a user with oidc
2. delete the user
3. login again

**Expected behavior**
unlink previously linked user(which is already deleted), re-create the user and link

**Logs**
```
[10:17:32] [ERR] [207] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL POST /sso/OID/Auth/kanidm.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateEntry(Object entity, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.EntryWithoutDetectChanges(TEntity entity)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Update(TEntity entity)
   at Jellyfin.Server.Implementations.Users.UserManager.UpdateUserAsync(User user)
   at Jellyfin.Server.Implementations.Users.UserManager.UpdateUserAsync(User user)
   at Jellyfin.Plugin.SSO_Auth.Api.SSOController.Authenticate(Guid userId, Boolean isAdmin, Boolean enableAuthorization, Boolean enableAllFolders, String[] enabledFolders, AuthResponse authResponse, String defaultProvider)
   at Jellyfin.Plugin.SSO_Auth.Api.SSOController.OidAuth(String provider, AuthResponse response)
   at lambda_method2151(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
```

**Versions (please complete the following information):**

- OS: Linux
- Browser: chrome
- Jellyfin Version: 10.8.9
- Plugin Version: 3.4.0.0

**Probably solution**
1. unlink user while deleting it
2. or delete the link on login when found user is deleted

**Comment by 9p4** [comment]
dupe: https://github.com/9p4/jellyfin-plugin-sso/issues/98
