### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'collection')

### ISSUE THREAD

**Issue by skuizy** [9p4/jellyfin-plugin-sso#130]
**Describe the bug**
Whenever I try to login with authelia I get the `Error processing request.` message in my browser and logs says `System.ArgumentNullException: Value cannot be null. (Parameter 'collection')`

**To Reproduce**

1. Go to https://jellyfin.mydomain/sso/OID/p/authelia
2. Login with user
3. See error:
```
jellyfin         | 2023-08-05T14:37:38.249436382Z [14:37:38] [ERR] [105] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /sso/OID/r/authelia.
jellyfin         | 2023-08-05T14:37:38.249493188Z System.ArgumentNullException: Value cannot be null. (Parameter 'collection')
jellyfin         | 2023-08-05T14:37:38.249510230Z    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
jellyfin         | 2023-08-05T14:37:38.249524557Z    at Jellyfin.Plugin.SSO_Auth.Api.SSOController.OidPost(String provider, String state)
jellyfin         | 2023-08-05T14:37:38.249538935Z    at lambda_method688(Closure , Object , Object[] )
jellyfin         | 2023-08-05T14:37:38.249552445Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Obj
ect[] arguments)
jellyfin         | 2023-08-05T14:37:38.249566306Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
jellyfin         | 2023-08-05T14:37:38.249579795Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin         | 2023-08-05T14:37:38.249595044Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
jellyfin         | 2023-08-05T14:37:38.249634761Z --- End of stack trace from previous location ---
jellyfin         | 2023-08-05T14:37:38.249648997Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
jellyfin         | 2023-08-05T14:37:38.249662395Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin         | 2023-08-05T14:37:38.249676941Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
jellyfin         | 2023-08-05T14:37:38.249690498Z --- End of stack trace from previous location ---
jellyfin         | 2023-08-05T14:37:38.249703710Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Bo
olean isCompleted)
jellyfin         | 2023-08-05T14:37:38.249718290Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
jellyfin         | 2023-08-05T14:37:38.249731774Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
jellyfin         | 2023-08-05T14:37:38.249745731Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
jellyfin         | 2023-08-05T14:37:38.249758877Z --- End of stack trace from previous location ---
jellyfin         | 2023-08-05T14:37:38.249774145Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin         | 2023-08-05T14:37:38.249788388Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
jellyfin         | 2023-08-05T14:37:38.249802189Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
jellyfin         | 2023-08-05T14:37:38.249816002Z    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
jellyfin         | 2023-08-05T14:37:38.249830055Z    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
jellyfin         | 2023-08-05T14:37:38.249843353Z    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
jellyfin         | 2023-08-05T14:37:38.249857112Z    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
jellyfin         | 2023-08-05T14:37:38.249871029Z    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
jellyfin         | 2023-08-05T14:37:38.249884016Z    at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
jellyfin         | 2023-08-05T14:37:38.249897220Z    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
jellyfin         | 2023-08-05T14:37:38.249910257Z    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
jellyfin         | 2023-08-05T14:37:38.249923456Z    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
jellyfin         | 2023-08-05T14:37:38.249948070Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
jellyfin         | 2023-08-05T14:37:38.249961521Z    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
jellyfin         | 2023-08-05T14:37:38.249974702Z    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
jellyfin         | 2023-08-05T14:37:38.249988041Z    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
jellyfin         | 2023-08-05T14:37:38.250001249Z    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
jellyfin         | 2023-08-05T14:37:38.250027859Z    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Expected behavior**
Welcome to jellyfin web client

**Configuration**
Authelia :
```
    clients:
    - id: jellyfin
      secret: <redacted>
      authorization_policy: two_factor
      redirect_uris:
        - https://jellyfin.mydomain/sso/OID/r/authelia
      scopes:
        - openid
        - profile
        - groups
        - email
      userinfo_signing_algorithm: none
```
SSO-Auth.xml :
```
<?xml version="1.0" encoding="utf-8"?>
<PluginConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <SamlConfigs />
  <OidConfigs>
    <item>
      <key>
        <string>authelia</string>
      </key>
      <value>
        <PluginConfiguration>
          <OidEndpoint>https://authelia.mydomain</OidEndpoint>
          <OidClientId>jellyfin</OidClientId>
          <OidSecret>redacted</OidSecret>
          <Enabled>true</Enabled>
          <EnableAuthorization>false</EnableAuthorization>
          <EnableAllFolders>true</EnableAllFolders>
          <AdminRoles>
            <string>admin</string>
          </AdminRoles>
          <EnableFolderRoles>false</EnableFolderRoles>
          <RoleClaim>groups</RoleClaim>
          <OidScopes>
            <string>groups</string>
          </OidScopes>
          <CanonicalLinks />
        </PluginConfiguration>
      </value>
    </item>
  </OidConfigs>
</PluginConfiguration>
```

**Versions (please complete the following information):**

- OS: Linux/Docker (linuxserver/jellyfin)
- Browser: Firefox 115.0.2 (64 bits)
- Jellyfin Version: 10.8.10
- Plugin Version: 3.4.0.0

**Comment by 9p4** [comment]
Could you switch to nightly and see if the issue persists? I think the issue is that you have a null `Roles` block (which should be fixed now).

**Comment by 9p4** [comment]
Dupe: https://github.com/9p4/jellyfin-plugin-sso/issues/81

**Comment by skuizy** [comment]
Issue solved by adding `admin` value for `Roles` in the config.

Thanks !

**Comment by 9p4** [comment]
For future reference, this problem shouldn't ever happen again with the commit 1de72effca290083d3e7d5b78bcd3ba3e1c03601
