### ISSUE TITLE
UniFi ID SAML Error

### ISSUE THREAD

**Issue by huslage** [9p4/jellyfin-plugin-sso#141]
**Describe the bug**

I have set up a new SAML application in UniFi Identity (UID) that points to my Jellyfin instance. At first it was complaining about the ACS URL being wrong because it appears that the current documentation is wrong the URL to be set up. After analyzing the error response, I put the correct ACS URL into the UID config. Now I'm getting a valid [SAML Response](https://gist.github.com/huslage/2434ee20fe924f67294fffa3a7e07987), but the Linking page still shows an error (see log file with Base64 decode error in linked gist)

**To Reproduce**

* Configure the saml endpoint by doing a POST to: `/jellyfin/sso/SAML/Add/UID?api_key=[API_KEY]` (config.json in the linked Gist.
* Visit `jellyfin/SSOViews/linking` in the browser and click the + button.
* SAML linking begins and the IdP sends back a success, however the linking fails with `Error processing request.` when redirected to `jellyfin/sso/SAML/p/UID`
* Log file shows that the response was not parseable.
* Use `base64 -d -i file.b64` to verify that the response is indeed parseable (I can email you this base64 encoded response, but I don't want to share it publicly.)

**Expected behavior**
I would expect the successful response from the IdP would be parsed and the linking would succeed.

**Screenshots**
See this [Gist](https://gist.github.com/huslage/2434ee20fe924f67294fffa3a7e07987)

**Configuration**

See this [Gist](https://gist.github.com/huslage/2434ee20fe924f67294fffa3a7e07987)

**Versions (please complete the following information):**

- OS: MacOS 13.5.1
- Browser: Firefox
- Jellyfin Version: 10.8.10
- Plugin Version: 3.5.2.0

**Additional context**
Jellyfin Mac App from the website. Installed plugin from repo listed in README.md.

**Comment by 9p4** [comment]
Does the certificate in the configuration have linebreaks?

**Comment by huslage** [comment]
No. It looks like:

`"samlCertificate": “MIIEUTCCAzmg….NokEl0gKY”,`

**Comment by huslage** [comment]
In the SSO-Auth.xml:

`<SamlCertificate>MIIEUTCC...qiMiS5dznV1G7lNokEl0gKY</SamlCertificate>`

No line breaks.

**Comment by 9p4** [comment]
Is the Jellyfin server running on Windows, Linux, or something else?

**Comment by huslage** [comment]
It’s on MacOS 13.5.1 (as mentioned in the ticket) using the Jellyfin.app that I self-signed. It works great other than this issue.

**Comment by huslage** [comment]
It’s just signed.

**Comment by 9p4** [comment]
Does SAML login function correctly?

**Comment by huslage** [comment]
The binding never completes, so no.

**Comment by 9p4** [comment]
Not the linking, but if you just go to `jellyfin/sso/SAML/p/UID`, does the login succeed?

**Comment by huslage** [comment]
No, I get the same error in the logs:

```
[2023-09-01 10:14:54.227 -04:00] [ERR] [53] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/sso/SAML/p/UID".
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Jellyfin.Plugin.SSO_Auth.Api.SSOController.SamlPost(String provider, String relayState)
   at lambda_method1221(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Comment by 9p4** [comment]
Just to check the characters used in your SAML certificate, can you put the certificate into a file, then run `cat certificatefile.txt | grep -o . | sort | uniq`? This will give me a list of the characters. You might have a non-standard Base64 certificate that uses slightly different characters.

**Comment by 9p4** [comment]
Furthermore, are the assertions signed or documents signed?

**Comment by huslage** [comment]
Here's the character list:

```
+
0
1
2
3
4
5
6
8
9
=
A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
```

Nothing strange there. The assertions and documents are both signed.

**Comment by huslage** [comment]
I don’t have the option to customize any of the assertions. Is there a reason you don’t just accept the xml metadata and act accordingly?

**Comment by 9p4** [comment]
Enabling signed assertions in Keycloak still works for me. Unfortunately, I can't seem to get access to Unifi Identity, and it may make it harder for me to reproduce your issue. If you are willing, can you email me the unredacted public certificate that you are using? My contact information is at https://ersei.net/en/contact-me

**Comment by 9p4** [comment]
Is there any update?
