### ISSUE TITLE
SSO Linking creates new account instead of linking with existing local account

### ISSUE THREAD

**Issue by Dleewee** [9p4/jellyfin-plugin-sso#209]
**Describe the bug**

**To Reproduce**

1. Log in with a traditional "local account"'
2. Append /SSOViews/linking to the end of your instance URL
3. Select the "+" button next to your authentication provider
4. A whole new account is created, rather than establishing a link to the "local account"

**Expected behavior**
The existing local account should be linked to an SSO provider, allowing the user to use either their local credentials or the SSO login process.

**Screenshots**
"testuser" is logged in with local account
![image](https://github.com/user-attachments/assets/f2653c3f-091e-47fe-b1b9-0b1777dc5fe5)

Navigate to linking page and select plus button
![image](https://github.com/user-attachments/assets/e781e9b5-6bdd-4f26-bc18-227212b6ee21)

"test.user" account is logged in and is not connected to original "testuser" - instead a whole new account has been created
![image](https://github.com/user-attachments/assets/cfa3b96e-0856-4efa-83cd-0a0e0bbc0378)

![image](https://github.com/user-attachments/assets/67a8ce30-d885-4faa-a91d-144cc96b88b3)

**Configuration**
All settings below "OID Secret" have been left blank/default. I only completed the top 4 lines and checked the box for "enabled."

**Versions (please complete the following information):**

- OS: Official Jellyfin Docker container
- Browser: Firefox
- Jellyfin Version: 10.9.11
- Plugin Version: 3.5.2.4

**Additional context**
I am able to complete successful SSO login, however I cannot seem to tie/link SSO into an existing "local account" i.e. an account created directly in Jellyfin. I would like to link accounts so that previous watched status can be retained.

**Comment by 9p4** [comment]
I can't reproduce this on my end, can you upload a screencast of the steps you are taking?

**Comment by Dleewee** [comment]
Screencast: https://imgur.com/a/AAbPHfL
Login with local user "test"
Go to SSO Linking page and click +
Sign in to SSO account "test.user"
When returned to Jellyfin, am loged in with different, new account "test.user" not connected to original account "test"

**Comment by Dleewee** [comment]
Bump in hopes the screen recording helps. Seems likely I am doing something wrong and would love to get this working!

**Comment by 9p4** [comment]
Sorry, but I've been busy with classes. I'll take a look this week.

**Comment by Yersi88** [comment]
+1 exactly the same issue on my end (as seen in the video)
Upon clicking + in self-service page and authenticating with Authentik a new user account is created instead of linking to the account that was already logged in on Jellyfin.

**Comment by 9p4** [comment]
@strazto any thoughts?

**Comment by daleao** [comment]
Same issue happening on my end with Authelia, except instead of creating a parallel user, it seems to overwrite my existing user. The real issue is that this removes my administrator privileges in Jellyfin.

Steps:
- Followed the steps [here](https://www.authelia.com/integration/openid-connect/jellyfin/).
- Made sure to set `<DefaultUsernameClaim>name</DefaultUsernameClaim>` in `SSO-Auth.xml` so linking should happen with Authelia's Display Name field, and ensured that `displayname` in Authelia's `users_database.yml` matches my Jellyfin username.
- Made sure to include <RoleClaim>groups</RoleClaim>` and `<AdminRoles><string>admins</string></AdminRoles>` in `SSO-Auth.xml`, so my user should receive admin role anyway. Ensured that `groups` in Authelia's `users_database.yml` includes `- admins`.
- Clicked to sign in with single sign on.
- Accepted the promp by Authelia to approve the linking request.

Expected result:
Authelia user is linked to Jellyfin user of the same name. Either no changes are made since the user already existed, or the user is granted admin privileges.

Result: I am logged in with correct user name, but have no admin privileges. If I log out and try to log back in manually, my password still works, but still no privileges, which means they were effectively overwritten during the linking process.
I checked the value of `<CanonicalLinks>` in `SSO-Auth.xml` and it seems to have linked correctly (user GUID matches the original user's ID).

**Comment by Codixer** [comment]
Same issue, here is another video:
https://github.com/user-attachments/assets/3c2a0487-89aa-4c20-a359-e73c1447068a

**Comment by terinjokes** [comment]
I'm noticing that there is never an XHR to the `sso/{mode}/Link/{provider}` endpoint, despite the returned HTML containing `if (true) await link(request);`. There's a few early returns, but Firefox is making it difficult to set breakpoints on an inline script, so I'm not sure which path is being taken.

If in a linking flow, any errors to link, either the current early returns or the XHR onerror function being called, should cause an error to be shown, rather than continuing forward with the call to `sso/{mode}/Auth/{provider}`, as this creates a new user if one is not already linked.

**Comment by Codixer** [comment]
@Dleewee so my guess here, the plugin currently uses the username of the sso. Not the fact it wants to link to an account. So yes, it works. But it does it by returning to the endpoint used for logging in instead of a seperate endpoint for linking.

**Comment by Dleewee** [comment]
> @Dleewee so my guess here, the plugin currently uses the username of the sso. Not the fact it wants to link to an account. So yes, it works. But it does it by returning to the endpoint used for logging in instead of a seperate endpoint for linking.

I see, so it requires that the SSO username exactly match the existing Jellyfin user name in order to create a linkage, otherwise it creates a new user. 

I will suggest this is an opportunity for enhancement, by allowing me to link any existing user with any SSO ID that I am able to authenticate with. For comparison, you may look at Bookstack as well as NextCloud Social. Both of these projects allow linking a SSO account with an existing local account and have no requirement that the usernames be the same. 

Thanks!

**Comment by Yersi88** [comment]
> > @Dleewee so my guess here, the plugin currently uses the username of the sso. Not the fact it wants to link to an account. So yes, it works. But it does it by returning to the endpoint used for logging in instead of a seperate endpoint for linking.
> 
> I see, so it requires that the SSO username exactly match the existing Jellyfin user name in order to create a linkage, otherwise it creates a new user.
> 
> I will suggest this is an opportunity for enhancement, by allowing me to link any existing user with any SSO ID that I am able to authenticate with. For comparison, you may look at Bookstack as well as NextCloud Social. Both of these projects allow linking a SSO account with an existing local account and have no requirement that the usernames be the same.
> 
> Thanks!

+1 for the enhancement, I also had no idea that the SSO username had to match the Jellyfin username exactly. I just assumed it will link the Jellyfin account that's currently logged in, to the SSO account that gets authenticated during the linking process.

**Comment by terinjokes** [comment]
I think it's supposed to, but due to the bug I mentioned in https://github.com/9p4/jellyfin-plugin-sso/issues/209#issuecomment-2453117777 it no longer does so.

**Comment by Mavyre** [comment]
Same issue here. Here is what I got in the logs:

`[2024-11-17 18:58:31.071 +01:00] [INF] [11] Jellyfin.Plugin.SSO_Auth.Api.SSOContr
oller: Is request linking: True                                                  
[2024-11-17 18:58:31.820 +01:00] [INF] [11] Jellyfin.Plugin.SSO_Auth.Api.SSOContr
oller: SSO Controller initialized                                                
[2024-11-17 18:58:31.821 +01:00] [INF] [11] Jellyfin.Plugin.SSO_Auth.Api.SSOContr
oller: SSO user bastien@home.vydees.net doesn't exist, creating...               
[2024-11-17 18:58:32.449 +01:00] [INF] [11] Jellyfin.Plugin.SSO_Auth.Api.SSOContr
oller: SSO user link doesn't exist, creating...                                  
[2024-11-17 18:58:32.470 +01:00] [INF] [11] Jellyfin.Plugin.SSO_Auth.Api.SSOContr
oller: Auth request created...                                                   
[2024-11-17 18:58:32.485 +01:00] [INF] [11] Jellyfin.Plugin.SSO_Auth.Api.SSOContr
oller: Set default login provider to Jellyfin.Plugin.LDAP_Auth.LdapAuthentication
ProviderPlugin`

**Comment by 9p4** [comment]
I think you are passing the username claim in as an email address instead of the exact value that Jellyfin wants?

**Comment by PJGitHub9** [comment]
Same issue here, would love to be able to link an existing user. I try mapping my admin account to authentik and it just creates a new user (different username in JF and Authentik)

**Comment by holdenfershee** [comment]
I am having the same issue. I did setup via GUI, though. It allows login through SSO, and then when SSOlinking, I get a new user with the ugly: **e3a7f6d2-49b1-5c83-91d2-7c854a66e1f9** style username instead of the nicer **testuser** which I am trying to link to. Maybe I just need to manually change something via API? Thanks in advance for any help.

**Comment by 9p4** [comment]
Make sure the username claim is set to `preferred_username` and that the data is being passed from your SSO server to Jellyfin.

**Comment by holdenfershee** [comment]
Maybe I'm just confused on how this is supposed to work, but it looks like its creating the new user then trying to link it. Is that the intended behavior, or is the link supposed to dump you directly into test user. For example, if I have **testuser** as a user in Jellyfin and I am logging in with user@gmail.com through sso, it creates a user with that user id, instead of loggin me into **testuser**'s account. Is that intended?

Logs:
```19:39:57] [INF] [22] Jellyfin.Plugin.SSO_Auth.Api.SSOController: Is request linking: True
[19:39:58] [INF] [22] Jellyfin.Plugin.SSO_Auth.Api.SSOController: SSO Controller initialized
[19:39:58] [INF] [22] Jellyfin.Plugin.SSO_Auth.Api.SSOController: SSO user b9ce8694-2f94-86a3-5472-79998d633775 doesn't exist, creating...
[19:40:03] [INF] [22] Jellyfin.Plugin.SSO_Auth.Api.SSOController: SSO user link doesn't exist, creating...
[19:40:05] [INF] [22] Jellyfin.Plugin.SSO_Auth.Api.SSOController: Auth request created...
[19:40:06] [INF] [22] Jellyfin.Plugin.SSO_Auth.Api.SSOController: Set default login provider to Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider
[19:40:06] [INF] [22] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user b9ce8694-2f94-5472-86a3-8d6379993775: 0/0
[19:40:06] [INF] [22] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user ef096ca2-29d1-4ca8-88d6-ed064e45dd29````

**Comment by holdenfershee** [comment]
It is set to ```preferred_username```, sorry I forgot to mention that. Where should I check that everything is making it to Jellyfin from the SSO provider?

**Comment by Goaten** [comment]
I have the same issue with authenik. 

Authentik username: test
Jellyfin username: jellytest

In jellyfin I've set the "Set Default username claim" to "preferred_username"
In authentik I've created a Property Mapping for my jellyfin provider that will alter the preferred_username from "test" to "jellytest" which I can see works when looking at the user's JWT payload for the jellyfin provider in authentik. (see image)

But when I go through the process of linking the "jellytest" user to the authentik "test" user, it still creates a new user called "test" in jellyfin. It seems like the "preferred_username" is not used even though this is specified in the SSO plugin settings? Or there's something else going on that I don't understand.
I've also tested making the property mapping change both the "name" and "given_name" property to "jellytest", but that wasn't the issue.

![Image](https://github.com/user-attachments/assets/fc57cbf8-2d52-46e2-8029-d8e9c31eedec)

**Comment by Julusian** [comment]
I am seeing this too.
If the username between the local user and authentik differ, it creates a new account.
If the usernames match, it fails with the page getting stuck, and this gets written to the jellyfin log:
```
[2025-03-19 17:02:54.309 +00:00] [ERR] Error processing request. URL "POST" "/sso/OID/Auth/authentik".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.SSO_Auth.Api.SSOController.Authenticate(Guid userId, Boolean isAdmin, Boolean enableAuthorization, Boolean enableAllFolders, String[] enabledFolders, Boolean enableLiveTv, Boolean enableLiveTvAdmin, AuthResponse authResponse, String defaultProvider)
   at Jellyfin.Plugin.SSO_Auth.Api.SSOController.OidAuth(String provider, AuthResponse response)
   at lambda_method760(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```
I had to manually modify the plugin config, to remove stale `CanonicalLinks` entries to make this go away, but after doing this a few times the error stopped appearing. Not sure what I started doing differently.

By renaming the local user to match what authentik was creating. But it appears that if I try to undo the local account rename then the link breaks.  
So it looks to me like it is matching exclusively on the username, so if they differ or get changed then the linking will break. Reading through the code, I find the same conclusion. 

For now I can live with making the usernames match on both sides, I have changing usernames disabled in authentik so I shouldnt have a problem with this, but it does feel a bit brittle.  
Ideally I would expect that the linking to be tracking some immutable userId from authentik, and only using the username when creating a new jellyfin account. But maybe this will have issues if the `CanonicalLinks` Map gets mangled, or if the users get unlinked.

**Comment by matthew-thomas690** [comment]
The issue is on line 780 on the SSOController.cs

`        User user = null;

        // First try to get the user by its id in case it was already registered before
        Guid userId = Guid.Empty;
        try
        {
            userId = GetCanonicalLink(mode, provider, canonicalName);
        }
        catch (KeyNotFoundException)
        {
            userId = Guid.Empty;
        }

        // No userId found? Let's try and find the user by name instead
        if (userId == Guid.Empty)
        {
            user = _userManager.GetUserByName(canonicalName);
        }
        else
        {
            user = _userManager.GetUserById(userId);
        }

It is never loading the CanonicalLinks or at least it isn't able to pull out the Jellyfin user IDs which are being stored in a  serialized dictionary. This means that the userId is already set to empty and as a result the code always falls back to looking for the user based on the canonicalName instead.

It doesn't find a user that matches the canonicalName so then goes ahead and creates a new jellyfin user using the canonicalName as the username.

It's probably a simple fix but alas, I am not a contributor.

**Comment by ISlip3890** [comment]
Is there a known workaround for v3.5.2.4 apart from utilising:
 > https://github.com/matthew-thomas690/jellyfin-sso-oidc

I'm attempting to get my Microsoft Entra ID (previously Azure AD) SSO to work with the account linkage link. However I'm also experience the issues in this thread.
