### ISSUE TITLE
Error processing request. when adding either SAML or OpenID

### ISSUE THREAD

**Issue by Pfuenzle** [9p4/jellyfin-plugin-sso#4]
I successfully installed the plugin using Jellyfin with Version: 10.8.0 with the LinuxServer Docker Image.
The Plugin version that got installed is 2.0.0.0

Im also using Keycloak, like you, and created a client according to the documentation.

But when I try to add any configuration using curl, I get the error "Error processing request."

My commands are as following:

`curl -v -X POST -H "Content-Type: application/json" -d '{"samlEndpoint": "https://<redacted>/auth/realms/master/protocol/saml", "samlClientId": "jellyfin", "samlCertificate": "<redacted>", "enabled": true, "enableAllFolders": true, "enabledFolders": [], "adminRoles": [], "roles": []}' "https://<redacted>/sso/SAML/Add?api_key=<redacted>"`

for SAML and

`curl -v -X POST -H "Content-Type: application/json" -d '{"oidEndpoint": "https://<redacted>/auth/realms/master", "oidClientId": "jellyfin", "oidSecret": "<redacted>", "enabled": true, "enableAllFolders": true, "enabledFolders": [], "adminRoles": [], "roles": []}' "https://<redacted>/sso/SAML/Add?api_key=<redacted>"`

for OpenID. 

The error thats coming up in the Log for OpenID is the following:

```
[13:29:21] [INF] [74] Jellyfin.Plugin.SSO_Auth.Api.SSOController: SSO Controller initialized
[13:29:21] [ERR] [74] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL POST /sso/OID/Add.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.SSO_Auth.Api.SSOController.OIDAdd(OIDConfig oidConfig)
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass33_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.VoidResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

I cant read anything out of this error, do you have any idea why im getting it?

All other OpenID integrations are working fine, so I guess it got something to do with the plugin.

Thanks a lot for your plugin btw, really a shame that this hasnt been integrated into Jellyfin.

Bit Offtopic:
In the README.me in the OpenID curl command, the endpoint you specified is `"https://keycloak.example.com/auth/reapls/test"`
I guess this is a typo and should spell realms instead of reapls?

**Comment by 9p4** [comment]
Thanks for the issue. What's in your configuration file? (`config/plugins/configurations/SSO-Auth.xml`)

**Comment by 9p4** [comment]
Alright, it seems like an artifact wasn't loaded in the plugin zip. Try updating the plugin now and let me know if it works.

**Comment by Pfuenzle** [comment]
Thanks a lot for the fast response!
After the update I was able to add it without any issues and the OID Integration is working like a dream.

Thanks a lot again, this is really great :)
