### ISSUE TITLE
Authentik - Login process stuck

### ISSUE THREAD

**Issue by basbebe** [9p4/jellyfin-plugin-sso#96]
**Describe the bug**
Similar to #88 my login attempt from Authentik stops at "Logging in..."

**To Reproduce**

1. Go to 'https://jellyfin.domain.tld/sso/oid/p/auth.domain.tld'
2. Authentik redirection can be seen
3. Next page only shows "Logging in..."

**Expected behavior**
I expect to be logged in.

**Screenshots**

<img width="1087" alt="Screen Shot 2022-11-03 at 19 30 05" src="https://user-images.githubusercontent.com/7083188/199808014-2a57bffb-2298-44dd-8f2b-684a11d47022.png">

<img width="544" alt="Screen Shot 2022-11-03 at 19 31 23" src="https://user-images.githubusercontent.com/7083188/199808026-7a96388a-a40c-4146-8427-044231447679.png">

**Configuration**

Deployed on TrueNAS via Truecharts/Kubernetes, therefore screenshots of config.

<img width="824" alt="Screen Shot 2022-11-03 at 19 37 48" src="https://user-images.githubusercontent.com/7083188/199808097-ba27f868-9571-4ef0-98e4-4074a11d03e1.png">
<img width="791" alt="Screen Shot 2022-11-03 at 19 39 03" src="https://user-images.githubusercontent.com/7083188/199808234-9881c82f-934f-4ac8-a923-98cc44e9c436.png">
<img width="787" alt="Screen Shot 2022-11-03 at 19 39 47" src="https://user-images.githubusercontent.com/7083188/199808246-005afe9d-1f65-4a19-9938-3d5dd82df93c.png">

**Versions (please complete the following information):**

- OS: macOS
- Browser: Chromium & Firefox
- Jellyfin Version: 10.8.6
- Plugin Version: 3.4.0.0

**Additional context**

Authentik config:
<img width="1108" alt="Screen Shot 2022-11-03 at 19 41 19" src="https://user-images.githubusercontent.com/7083188/199808346-9610cbca-c140-4ae3-92fd-7a697888420c.png">
<img width="1087" alt="Screen Shot 2022-11-03 at 19 42 26" src="https://user-images.githubusercontent.com/7083188/199808353-f5ba9753-8c42-480f-94b4-8fa9d722955d.png">
<img width="1077" alt="Screen Shot 2022-11-03 at 19 43 22" src="https://user-images.githubusercontent.com/7083188/199808375-1e0a3fa4-d836-4ceb-bd69-f197c5760634.png">

**Comment by 9p4** [comment]
Could you please upload the logs from Jellyfin?

**Comment by basbebe** [comment]
```console
2022-11-03T21:54:26.724907244Z [22:54:26] [INF] [61] Jellyfin.Plugin.SSO_Auth.Api.SSOController: SSO Controller initialized
2022-11-03T21:54:27.272924717Z [22:54:27] [WRN] [72] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from https://jellyfin.domain.tld/sso/oid/p/auth.domain.tld to 192.168.X.X in 0:00:00.5481268 with Status Code 302
2022-11-03T21:54:27.618625389Z [22:54:27] [INF] [61] Jellyfin.Plugin.SSO_Auth.Api.SSOController: SSO Controller initialized
2022-11-03T21:54:29.963338468Z [22:54:29] [INF] [61] Jellyfin.Plugin.SSO_Auth.Api.SSOController: Is request linking: False
2022-11-03T21:54:29.963812930Z [22:54:29] [WRN] [61] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from https://jellyfin.domain.tld/sso/OID/r/auth.domain.tld?code=2e8bdc14e02144fab8a5fcbfc12c7920&state=IYJ6MXd0JKqFLSTreD8D5Q to 192.168.X.X in 0:00:02.3452509 with Status Code 200
2022-11-03T21:54:29.999850226Z [22:54:29] [INF] [54] Jellyfin.Plugin.SSO_Auth.Api.SSOController: SSO Controller initialized
2022-11-03T21:54:30.001974217Z [22:54:30] [ERR] [54] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL POST /sso/OID/Auth/auth.domain.tld.
2022-11-03T21:54:30.002033457Z System.NullReferenceException: Object reference not set to an instance of an object.
2022-11-03T21:54:30.002040087Z    at Jellyfin.Plugin.SSO_Auth.Api.SSOController.Authenticate(Guid userId, Boolean isAdmin, Boolean enableAuthorization, Boolean enableAllFolders, String[] enabledFolders, AuthResponse authResponse, String defaultProvider)
2022-11-03T21:54:30.002055107Z    at Jellyfin.Plugin.SSO_Auth.Api.SSOController.OidAuth(String provider, AuthResponse response)
2022-11-03T21:54:30.002060508Z    at lambda_method468(Closure , Object )
2022-11-03T21:54:30.002065618Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2022-11-03T21:54:30.002076728Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2022-11-03T21:54:30.002082458Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2022-11-03T21:54:30.002093578Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2022-11-03T21:54:30.002098568Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2022-11-03T21:54:30.002114948Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
2022-11-03T21:54:30.002122118Z --- End of stack trace from previous location ---
2022-11-03T21:54:30.002127078Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2022-11-03T21:54:30.002139228Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2022-11-03T21:54:30.002144168Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2022-11-03T21:54:30.002156328Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
2022-11-03T21:54:30.002163158Z --- End of stack trace from previous location ---
2022-11-03T21:54:30.002169628Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2022-11-03T21:54:30.002185968Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2022-11-03T21:54:30.002193348Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2022-11-03T21:54:30.002198498Z    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
2022-11-03T21:54:30.002217148Z    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
2022-11-03T21:54:30.002223018Z    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
2022-11-03T21:54:30.002236828Z    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
2022-11-03T21:54:30.002243638Z    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2022-11-03T21:54:30.002250959Z    at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
2022-11-03T21:54:30.002271919Z    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
2022-11-03T21:54:30.002277269Z    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
2022-11-03T21:54:30.002282299Z    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
2022-11-03T21:54:30.002296449Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2022-11-03T21:54:30.002303609Z    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
2022-11-03T21:54:30.002309859Z    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
2022-11-03T21:54:30.002326909Z    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
2022-11-03T21:54:30.002333909Z    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
2022-11-03T21:54:30.002340769Z    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Comment by 9p4** [comment]
When you request additional scopes, please have it set to `groups` and not `["groups"]`

Dupe of https://github.com/9p4/jellyfin-plugin-sso/issues/91

**Comment by basbebe** [comment]
I got that from the [providers.md](https://github.com/9p4/jellyfin-plugin-sso/blob/main/providers.md)

Switched it to `groups`, restarted container, same problem.

**Comment by jmuchovej** [comment]
Can confirm that I too am having the same issue when attempting to do `Enable Authorization by Plugin`. Everything worked just fine with the basic setup (SSO enabled but nothing related to the user's group membership from Authentik).

The only differences between @basbebe's configuration screenshots and mine are:
- "Enable All Folders" (in Jellyfin) is disabled.
- "Set default Provider" (in Jellyfin) is left blank.
- "Scopes" (in Authentik) omits "email".

I get the exact error and

**Comment by 9p4** [comment]
What version of Authentik are you using?

**Comment by 9p4** [comment]
Have you enabled the scope for group membership?

**Comment by jmuchovej** [comment]
> What version of Authentik are you using?

`2202.10.0` (`2022.10.1` was released a few days ago, afaik. I can update to that if it's useful.)

<img width="480" alt="image" src="https://user-images.githubusercontent.com/5000729/200139407-b9a47586-6547-4f5b-b8c1-336517c31c91.png">



> Have you enabled the scope for group membership?

Indeed.

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/5000729/200139428-7eafd928-298c-4734-9756-8994c0132bee.png">

`groups` mirrors what's advised in [`providers.md`](../blob/main/providers.md#authentik).

**Comment by 9p4** [comment]
What is the response mode in Authentik?

**Comment by jmuchovej** [comment]
> What is the response mode in Authentik?

I'm not sure, but from [this issue][authentik_response_mode], it seems to depend – if I'm reading that issue correctly, Authentik's response mode would be a `query` (or perhaps a `fragment`, but I'm pretty sure this is an "authorization flow"). Is there a particular response mode that Jellyfin SSO is looking for? I saw that you asked for [this update][authelia_response_mode], but based on the issue opened with Authentik, it seems like I might not be able to control that. 😕 

[authentik_response_mode]: https://github.com/goauthentik/authentik/issues/1953
[authelia_response_mode]: https://github.com/9p4/jellyfin-plugin-sso/issues/88#issuecomment-1284397252

**Comment by 9p4** [comment]
The plugin works only with the `query` mode (due to a limitation to the upstream library)

**Comment by jmuchovej** [comment]
I see. I'm not too familiar with the ins-and-outs of OIDC/SSO – is there any way I can inspect (from the plugin) what the response mode that's coming in, is?

**Comment by 9p4** [comment]
afaik there isn't a way to do so without editing the code and compiling the plugin yourself. See the function `OidPost` in `SSOController.cs`

**Comment by jmuchovej** [comment]
So, I think I know what may have happened (no idea if this is a plugin or Jellyfin issue) – I created an account by SSO when initially setup, but had "Enable Authorization by Plugin" turned off, then (mistakenly?) deleted my newly create account, changed the setting, and proceeded to go about testing permissions/access using the reported roles.

I just finished wiping Jellyfin and reconfiguring it, started up with SSO, but turned on "Enable Authorization by Plugin" after the creating the default configuration (the one described in `providers.md`). Didn't delete my account this time and started using the roles for role-based library/admin access and everything appears to be working swimmingly.

SOO... I think the issue was that when I delete a user from Jellyfin, they aren't actually removed from wherever users are stored. (Dunno if this is an issue on Jellyfin SSO's part or Jellyfin proper. ¯\_(ツ)_/¯)

**Comment by 9p4** [comment]
> I think the issue was that when I delete a user from Jellyfin, they aren't actually removed from wherever users are stored. (Dunno if this is an issue on Jellyfin SSO's part or Jellyfin proper.

I could see that happening. The link between the SSO user and the Jellyfin user GUID still exists after the user is deleted. Can you make a new issue saying that deleting a user in Jellyfin will cause that SSO account to stop working?

**Comment by basbebe** [comment]
Well I _think_ what is happening for me is exactly what @jmuchovej experiences.

**Comment by esmondmissen** [comment]
This may be fixed with #99.

**Comment by esmondmissen** [comment]
@basbebe could you test with the latest nightly build. I think at least part of your issue should be resolved.

**Comment by basbebe** [comment]
Thanks!

For the Moment, the [workaround](https://github.com/9p4/jellyfin-plugin-sso/issues/98#issuecomment-1306545782) posted in #98 seems to solve my problem.

**Comment by Aterfax** [comment]
> Thanks!
> 
> For the Moment, the [workaround](https://github.com/9p4/jellyfin-plugin-sso/issues/98#issuecomment-1306545782) posted in #98 seems to solve my problem.

This solved it on my end when user login via SSO stopped working from Authentik.
